### ISSUE TITLE
Booting aarch64-laptops-bionic-prebuilt.img.xz on Lenovo Yoga C630 WOS cause "laptop.dtb not found" error

### ISSUE THREAD

**Issue by RussianNeuroMancer** [aarch64-laptops/build#10]
Hello!

I find that booting aarch64-laptops-bionic-prebuilt.img.xz on Lenovo Yoga C630 WOS cause following error message:

`error: file /boot/laptop.dtb not found.`

Copying /boot/laptop-lenovo-yoga-c630.dtb to /boot/laptop.dtb allow to boot normally.

**Comment by lag-linaro** [comment]
Could you point to the documentation that you're following please?

**Comment by RussianNeuroMancer** [comment]
I downloading prebuilt image as recommended [here](https://github.com/aarch64-laptops/build#use-an-existing-pre-built-image), then I flash image to microSD with balenaEtcher (as I understand this step shouldn't be different from using zcat and dd recommended [here](https://github.com/aarch64-laptops/build#flashing-the-image)). Next I disable Secure Boot as described [here](https://github.com/aarch64-laptops/build#disabling-secure-boot-on-the-lenovo-c630), and boot laptop from microSD adapter plugged into left USB port. 

Did I missed something?

**Comment by lag-linaro** [comment]
Yes, but it's not your fault.

The best ways to avoid this issue is to either build the image using `quick-start.sh` or flash it using `flash-prebuilt.sh` (from the `prebuilt` repo).  However, this was not documented in this repo's `README.md`.

We now have adequate documentation: https://github.com/aarch64-laptops/build/commit/7ac7b8244c17639e260d78a67937ce9ac75e5778

The `flash-prebuilt.sh` helper is now part of this repo: https://github.com/aarch64-laptops/build/commit/aefb51e1c4dd166ea2958f050f0b813f83407394

**Comment by RussianNeuroMancer** [comment]
> or flash it using flash-prebuilt.sh

I see, thank you for pointing me to this script!
