### ISSUE TITLE
Default swappiness to 0

### ISSUE THREAD

**Issue by daniel-thompson** [aarch64-laptops/build#3]
In almost all cases these laptops are based on flash media (some of which has no discard support and may even my soldered down) and have a fairly decent quantity of RAM. Whilst shipping with swap enabled is sensible to cope with a few bits and pieces it might be good to set a low value for swappiness so we prefer to flush the page cache (some of which will be clean so no writes happen) rather than write anonymous memory out to swap.

Setting swappiness should just be a matter of dropping a file into `/etc/sysctl.d` containing the following:
~~~
vm.swappiness = 0
~~~

**Comment by RussianNeuroMancer** [comment]
Do you have any scientific evidence that UFS 2.1 modules in three supported laptops can't handle amount of data swapped daily during light office/development work or web-browsing (remember it's Snapdragon 835 we talking about) with 4GB of RAM for lifespan of regular laptop/laptop? I tried to found such evidence regards eMMC year ago, but all I found was either outdated recommendations from SSD first days or rules of thumb on forums.

 UFS-based storage is supposed to be even more robust due to integrated controller that take care of wear leveling, bad-block management, ECC, etc.

**Comment by daniel-thompson** [comment]
I think eMMC and UFS will turn out to be a moot issue since we would expect installation to permanent storage to be handled by a distro installer (so tweaking the defaults in the rootfs images for removeable media will not affect them).

In other words setting up swappiness would be all about preserving the life of the SD card (for SD cards the potentially weak write performance is probably alone enough to encourage a low value for swappiness).

**Comment by RussianNeuroMancer** [comment]
I see, for users who run Linux with rootfs and swap on SD card that will make sense.

**Comment by ThomasKaiser** [comment]
ZRAM exists and all that's needed is adding Ubuntu's `zram-config` package (which unfortunately doesn't do the best job configuring ZRAM). With a disabled swapfile and only ZRAM the best `vm.swappiness` value is then 100 and the best algo is still lzo (due to [missing vector instructions support on ARM](https://forum.armbian.com/topic/8161-swap-on-sbc/)).

**Comment by lag-linaro** [comment]
Happy for this to be *solved* on a per-user basis, but considering that our main aim is to make this project redundant with a view to using only upstream components, making these sorts of changes on a project level seems surplus to requirement.

Closing.
