### ISSUE TITLE
Keyboard doesn't work with upstream Linux 5.4.0rc8 on Lenovo Yoga C630 WOS

### ISSUE THREAD

**Issue by RussianNeuroMancer** [aarch64-laptops/build#33]
Hello!

I found that keyboard doesn't work with Linux 5.4.0rc8 Snapdragon build installed from [mainline ppa](https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.4-rc8/) (unlike 5.3 from eoan repository builds from mainline ppa supposed to be based on upstream code with minimum changes that you can see in patches at the top of the page). I wonder if that config issue or upstream kernel actually missing some code that necessary for keyboard support?

**Comment by RussianNeuroMancer** [comment]
There is [dmesg](https://github.com/aarch64-laptops/build/files/3859973/dmesg540rc8.txt) of Linux 5.4.0rc8 boot.

**Comment by jallum** [comment]
I'm having the same problem with lack of keyboard while trying to upgrade with other versions of the mainline-snapdragon kernels that I've tried (5.3.0-*, 5.3.12-*, 5.4.0rc7).

my grub.cfg looks like:
```
        linux   /boot/vmlinuz-5.4.0-050400rc7-snapdragon root=UUID=f372934b-d8b1-4696-90db-e3f1b0bc73e8 ro quiet splash acpi=force efi=novamap clk_ignore_unused pd_ignore_unused
        initrd  /boot/initrd.img-5.4.0-050400rc7-snapdragon
        devicetree      /boot/dtb
```
...and I'm using the .dtb pulled from this repo:
```
md5:c19f0699173b656da04b2b057517e32c  sdm850-lenovo-yoga-c630.dtb
```

**Comment by RussianNeuroMancer** [comment]
In case of Linux 5.4.0rc8 Snapdragon build I using dtb shipped with the kernel (i.e. /etc/flash-kernel/dtb is empty).

**Comment by jallum** [comment]
Ah. Removing the `devicetree` line allowed me to boot kernel 5.4.0 (release; not rc), though with the same keyboard issues you're seeing.  My [dmesg](https://github.com/aarch64-laptops/build/files/3890015/dmesg540.txt) is a bit different, though our machines appear to be very similar.

**Comment by schmidtbag** [comment]
I'm also getting the same problem (using the generic kernel - I think the snapdragon kernel is specific to a different SoC).  Even without looking at my dmesg, I saw a lot of errors for I2C during bootup.  It's very possible that the keyboard is driven by I2C.
I also noticed as my system was booting up, there was an error for systemd-modules-load.  When checking the status for it, it says it failed to find the module "parport_pc".  Though, that's odd it bothered to mention that, since I don't think there are any parallel ports on these laptops.
[dmesg.log](https://github.com/aarch64-laptops/build/files/3965175/dmesg.log)

**Comment by RussianNeuroMancer** [comment]
https://lists.linaro.org/pipermail/aarch64-laptops/2020-February/000166.html

For me this workaround allowed to get keyboard working on Linux 5.5.4 and Linux 5.6.0rc2. [Reported to Ubuntu bugtracker](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1863761).
